### ISSUE TITLE
Deploy unter Windows

### ISSUE THREAD

**Issue by schchr** [UniversityOfWuerzburg-ChairCompSciVI/ueps#11]
https://github.com/UniversityOfWuerzburg-ChairCompSciVI/ueps/blob/master/src/test/resources

Beim Deployen unter Windows verursacht die Datei Probleme. Welches Verzeichnis muss da genau verlinkt werden ? Problem tritt sowohl in Bash als auch Dos auf.
![screenshot 2015-01-19 19 28 28](https://cloud.githubusercontent.com/assets/1575971/5805681/6335c4ba-a011-11e4-9aae-c43e00e75720.png)

**Comment by schchr** [comment]
okay habs einfach mal ressources aus main in test kopiert dann läufts. scheint also dass dieser "verzeichnis-link" unter windows nicht funktioniert und das das noch angepasst werden muss.

**Comment by schchr** [comment]
funktioniert jetzt (siehe #12)

**Comment by kolbasa** [comment]
Bug wurde gefixt. GitHub scheint auch symlinks zu synchronisieren. Damit habe ich nicht gerechnet.
