### ISSUE TITLE
userRights: Suche nach Benutzer gibt Exception

### ISSUE THREAD

**Issue by schchr** [UniversityOfWuerzburg-ChairCompSciVI/ueps#17]
Neue Rechte einrichten -> DropDown bei Benutzer/Eingabe bei Benutzer führt zu:

Request URI: /ueps/user_rights.xhtml
Ajax request: Yes
Status code: 500
Exception type: class javax.el.PropertyNotFoundException
Exception message: /user_rights.xhtml @236,83 completeMethod="#{user_names.rightsInit().complete}": Property 'rightsInit' not found on type de.uniwue.info6.webapp.misc.AutoCompleteUser

**Comment by kolbasa** [comment]
Welche Tomcat-Version nutzt du? 
Ich kann es bei mir nicht reproduzieren. 
![user_rights](https://cloud.githubusercontent.com/assets/3901582/5992929/86aed990-aa3e-11e4-9c2a-ad40e72536df.png)

**Comment by schchr** [comment]
problem besteht bei mir in tomcat7, wenn ich tomcat 8 nutze läufts erstaunlicherweise

**Comment by kolbasa** [comment]
Ich konnte den Bug auf dem Showcase-Server reproduzieren und habe diesen gleich gefixt.

Fehlermeldung fürs Archiv:
![dropdown_bug](https://cloud.githubusercontent.com/assets/3901582/6637442/b9b59864-c97a-11e4-8144-c1c0d67b9683.png)
