### ISSUE TITLE
Probleme bei der Kontrolle von User-Queries

### ISSUE THREAD

**Issue by schchr** [UniversityOfWuerzburg-ChairCompSciVI/ueps#24]
Szenario 1
Aufgabe 2
"SELECT title FROM books WHERE id=4"

Ist vom Ergebnisvergleich logischerweise richtig, ~~aber es findet kein statischer Vergleich statt.~~

Edit: statischer Vergleich findet statt, wird allerdings werden dessen Ergebnisse nicht angezeigt. War das richtig so?

**Comment by ghost** [comment]
war geklärt
